<?php

 

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://www.instagram.com/graphql/query/?query_hash=298b92c8d7cad703f7565aa892ede943&variables={%22tag_name%22:%22sunny%22,%22first%22:12}");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


$headers = array();
$headers[] = "Authority: www.instagram.com";
$headers[] = "Cache-Control: max-age=0";
$headers[] = "Upgrade-Insecure-Requests: 1";
$headers[] = "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36";
$headers[] = "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9";
$headers[] = "Sec-Fetch-Site: none";
$headers[] = "Sec-Fetch-Mode: navigate";
$headers[] = "Sec-Fetch-User: ?1";
$headers[] = "Sec-Fetch-Dest: document";
$headers[] = "Accept-Language: en-US,en;q=0.9,ar;q=0.8";
$headers[] = "Cookie: mid=W2xJpQAEAAH8kuwNcjfnXiFzFudD; mcd=3; csrftoken=MZUBdKI3d2YLGdyTlaq5yo3kI9geYC9h; ds_user_id=3297820541; sessionid=3297820541%3AMjHHoysLaTRbZS%3A5; ig_did=C88C1B3E-9106-4137-8284-5FF89CE84FE6; fbm_124024574287414=base_domain=.instagram.com; shbid=7558; shbts=1606650857.3331764; rur=ASH; fbsr_124024574287414=XSHNL2ouwu24YkaKzQV6jXBPBcWxIzap9RruP6nfVFg.eyJ1c2VyX2lkIjoiMTQ3NTEyMDIzNyIsImNvZGUiOiJBUUJZTWFieVZIVWlmQ243RlpYMnhBSlhuaUwtUk80WDVUUWJsY2djSkZfY2w3cU1OTTN2RXczSDQzYmRsODV1TzRCdi1HeU8xWXhvSTUzY2pkOGhMa21zLTVXWkpLbms3aU1TYXR6bnRmQnBRSFRpU3lIaER6NkhWWGZVWjFXMTNZRmJDanA3MmZnckdFaVpMREVFdndlTGZCS2FPdGFWSkFtbGcwclF1MzktR3ZBRnJ3Nmh4cGpfVWJLNWpvN1dnSXplWXEzMGNBdWkyV25xZkpoWnd1ME42bElMNXFaYXBKVzgySDZWaW1KLXBWTlBBcTdyTTNOTnh1LV9wYmRUMktPQW9VQS1EcHhkMDljVS1VcEdhTnpkRTc1NjVjdW5qYzJBZldiZUZMT21RRDNMQWlyWDNoeVBqUWMwb3g1YWFsMCIsIm9hdXRoX3Rva2VuIjoiRUFBQnd6TGl4bmpZQkFDT3Z0aFdaQVJETXAzb0xEd3ZUaFpDcW1Hc2ZENUlpVkZsQzVCRzY3aXE0NE1yZVh5c0l4R0RjcHpDSjRma0VHcnlnS0ZIVWp0aUZ5eEV2Z3VySUxIaVNLTllxZGFOaU82QnF1MWN4VWpwSFpDN281NktDQ0lWa0ZnUFpBYXFwWE5hMmJZVHpLTWY4WkJjY0VqWkEzdTZhc1pDSklLd1B0ZVhCbGNCcWpEdSIsImFsZ29yaXRobSI6IkhNQUMtU0hBMjU2IiwiaXNzdWVkX2F0IjoxNjA2NjU4NDI0fQ; urlgen=\"{\"154.237.141.7\": 36992054 \"154.237.203.11\": 36992}:1kjNKO:DETvh_X8BH42otyZ1G4GNrg_hXA\"";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
	echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

echo $result;
exit;

?>